### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Xiaminou** [daveyliam/mapwriter#41]
Original Issue: https://github.com/tterrag1098/WAILAPlugins/issues/47#event-350097474
Using mapwriter in Opis

**Comment by Vectron** [comment]
i fixed this in my version.
will take it out of beta this weekend and post in on curse.
https://www.dropbox.com/s/s4mzbyfuozc6pbu/MapWriter-1.7.10-2.1.5-Beta-2.jar?dl=0

**Comment by Badcholo** [comment]
dang i'm still crashing on start up from mapwriter on forge 1492

**Comment by Vectron** [comment]
need a bit more information then that.....
what version of mc?
what version of mapwriter?
crashlog?

**Comment by Badcholo** [comment]
Sry i'll post a crash log when i get home, i'm at work atm, i'll also provide client and server clean logs.
In the crash log it says mapwriter and a bunch of colored forced blocks. I haven't been able to disable anything in the configs.
MC 1.7.10 , 
Opis-1.2.5_1.7.10.jar
MobiusCore-1.2.5_1.7.10.jar

Thanks for a reply, i really need to find out what mod is causing my tps to drop on the server.

**Comment by Vectron** [comment]
aaah you are using opis....

i cant directly fix the problem there. but what you could try is open the latest mapwriter jar with a zip program. and copy the assets folder, mapwriter folder and the mapwriter file to the opis jar.

this should update all of the mapwriter code in opis and fix your bug.

note: this might introduce new bugs.

**Comment by Badcholo** [comment]
Thanks i'll try that. I'll test out just mapwriter first to make sure it works then i'll try adding it.
Any way to disable mapwriter from opis temporarily??, i really need to provide proof that a certain mod is causing lag.

**Comment by Badcholo** [comment]
omfg dude your a freaking genius!! it worked!!

**Comment by Badcholo** [comment]
it doesn't work on the server due to genchesthooks errors.
http://pastebin.com/4cheJui1
It seems it is happening to everyone that uses cauldron, but there is no support for it :-(

**Comment by Vectron** [comment]
I doubt it's realy fixable, i'm just making a guess here but what i think the problemen is:

Mobiuscore modifies base classes and this works fine in normale forge. But in cauldron those classes are already modifies so the changed from mobiuscore will interfere with thr code.

As for not suporting cauldron i agree, cauldron changes forge in the wrong way. There is nothing wrong with adding forge and spigot, but that shouldnt change the working of forge
